version: '3.8'

services:
  harmony-api:
    image: ${dockerhub_username}/harmony-api:latest
    container_name: harmony-api
    ports:
      - "8000:8000"
    environment:
      - EARTHDATA_USERNAME=${EARTHDATA_USERNAME}
      - EARTHDATA_PASSWORD=${EARTHDATA_PASSWORD}
      - SECRET_KEY=${SECRET_KEY:-plume}
      - API_VERSION=${API_VERSION:-1.0.0}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

